services:
    zotero-pdf2zh:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - ZOTERO_PDF2ZH_FROM_IMAGE=byaidu/pdf2zh:latest
                - ZOTERO_PDF2ZH_SERVER_FILE_DOWNLOAD_URL=https://raw.githubusercontent.com/guaguastandup/zotero-pdf2zh/refs/tags/v2.2.3/server.py
        container_name: zotero-pdf2zh
        restart: unless-stopped
        ports:
            - 8888:8888
        environment:
            - TZ=Asia/Shanghai
            - HF_ENDPOINT=https://hf-mirror.com
        volumes:
            - ./translated:/app/translated
            - ./config.json:/app/config.json
            - ./fonts:/app/fonts

